package graphicseditor;

public class EditShapes extends javax.swing.JInternalFrame {

    /**
     * Creates new form EditShapes
     */
    public EditShapes() {
        initComponents();
        System.out.println("I am in the contructor");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        line_width = new javax.swing.JButton();
        line_style = new javax.swing.JButton();
        fill_color = new javax.swing.JButton();
        fillStyle = new javax.swing.JButton();

        line_width.setText("linewidth");

        line_style.setText("linestyle");

        fill_color.setText("fillColor");

        fillStyle.setText("fillStyle");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(line_width)
                    .addComponent(line_style)
                    .addComponent(fill_color)
                    .addComponent(fillStyle))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(line_width)
                .addGap(33, 33, 33)
                .addComponent(line_style)
                .addGap(31, 31, 31)
                .addComponent(fill_color)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(fillStyle)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fillStyle;
    private javax.swing.JButton fill_color;
    private javax.swing.JButton line_style;
    private javax.swing.JButton line_width;
    // End of variables declaration//GEN-END:variables
}
