
package graphicseditor;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import javax.imageio.ImageIO;


public class Load extends javax.swing.JFrame {

    private PaintSurface paint_surface;

    /**
     * Creates new form Load
     */
    public Load(PaintSurface ps) {
        paint_surface = ps;
        initComponents();

        done.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Thread t = new Thread(new Runnable(){

                    public void run(){
                        String file = filename.getText();
                        try {
                            ObjectInputStream oin = new ObjectInputStream(new FileInputStream(file+"Rect.ser"));
                            paint_surface.setRect_array((ArrayList<Rect>)oin.readObject());
                            paint_surface.setNum_rect(paint_surface.getRect_array().size());
                            oin.close();
                            oin = new ObjectInputStream(new FileInputStream(file+"Ellipse.ser"));
                            paint_surface.setEllipse_array((ArrayList<Ellipse>)oin.readObject());
                            paint_surface.setNum_ellipse(paint_surface.getEllipse_array().size());
                            oin.close();
                            oin = new ObjectInputStream(new FileInputStream(file+"Line.ser"));
                            paint_surface.setLine_array((ArrayList<Line>)oin.readObject());
                            paint_surface.setNum_line(paint_surface.getLine_array().size());
                            oin.close();
                            oin = new ObjectInputStream(new FileInputStream(file+"group.ser"));
                            paint_surface.setGroup_array((ArrayList<grouping>) oin.readObject());
                            oin.close();
                            oin = new ObjectInputStream(new FileInputStream(file+"Images.ser"));
                            paint_surface.getImages().add(ImageIO.read(oin));
                            oin.close();
                            oin = new ObjectInputStream(new FileInputStream(file+"Img_Rect.ser"));
                            paint_surface.setImg_rect((ArrayList<Rect>) oin.readObject());
                            oin.close();
                            paint_surface.repaint();
                            } catch (FileNotFoundException e) {
                            // TODO Auto-generated catch block
                            e.printStackTrace();
                            } catch (IOException e) {
                            // TODO Auto-generated catch block
                            e.printStackTrace();
                            } catch (ClassNotFoundException e) {
                            // TODO Auto-generated catch block
                            e.printStackTrace();
                            }
                        dispose();
                    }

                });
                t.start();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        done = new javax.swing.JButton();
        filename = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        done.setText("ok");
        done.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(done)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(filename, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(filename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(done)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton done;
    private javax.swing.JTextField filename;
    // End of variables declaration//GEN-END:variables
}
