
package graphicseditor;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


public class PanArea extends javax.swing.JFrame {

    PaintSurface paint_surface;
    /**
     * Creates new form PanArea
     */
    public PanArea(PaintSurface ps) {
        this.paint_surface = ps;
        initComponents();
        Down.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
               Thread t = new Thread(new Runnable(){

                  public void run(){
                      for (Rect r: paint_surface.getRect_array()){
                          r.PanPos(0,Float.parseFloat(value.getText()));
                      }
                      for (Line l: paint_surface.getLine_array()){
                          l.PanPos(0,Float.parseFloat(value.getText()));
                      }
                      for (Ellipse e: paint_surface.getEllipse_array()){
                          e.PanPos(0,Float.parseFloat(value.getText()));
                      }
                      paint_surface.repaint();
                  }
               });
               t.start();
            }
        });
        up.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
               Thread t = new Thread(new Runnable(){

                  public void run(){
                      for (Rect r: paint_surface.getRect_array()){
                          r.PanPos(0,-Float.parseFloat(value.getText()));
                      }
                      for (Line l: paint_surface.getLine_array()){
                          l.PanPos(0,-Float.parseFloat(value.getText()));
                      }
                      for (Ellipse e: paint_surface.getEllipse_array()){
                          e.PanPos(0,-Float.parseFloat(value.getText()));
                      }
                      paint_surface.repaint();
                  }
               });
               t.start();
            }
        });
        Right.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
               Thread t = new Thread(new Runnable(){

                  public void run(){
                      for (Rect r: paint_surface.getRect_array()){
                          r.PanPos(Float.parseFloat(value.getText()),0);
                      }
                      for (Line l: paint_surface.getLine_array()){
                          l.PanPos(Float.parseFloat(value.getText()),0);
                      }
                      for (Ellipse e: paint_surface.getEllipse_array()){
                          e.PanPos(Float.parseFloat(value.getText()),0);
                      }
                      paint_surface.repaint();
                  }
               });
               t.start();
            }
        });
        Left.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
               Thread t = new Thread(new Runnable(){

                  public void run(){
                      for (Rect r: paint_surface.getRect_array()){
                          r.PanPos(-Float.parseFloat(value.getText()),0);
                      }
                      for (Line l: paint_surface.getLine_array()){
                          l.PanPos(-Float.parseFloat(value.getText()),0);
                      }
                      for (Ellipse e: paint_surface.getEllipse_array()){
                          e.PanPos(-Float.parseFloat(value.getText()),0);
                      }
                      paint_surface.repaint();
                  }
               });
               t.start();
            }
        });
        exit.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
               Thread t = new Thread(new Runnable(){

                  public void run(){
                      dispose();
                  }
               });
               t.start();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        up = new javax.swing.JButton();
        Down = new javax.swing.JButton();
        Left = new javax.swing.JButton();
        Right = new javax.swing.JButton();
        value = new javax.swing.JTextField();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        up.setText("Up");

        Down.setText("Down");

        Left.setText("Left");

        Right.setText("Right");

        value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueActionPerformed(evt);
            }
        });

        exit.setText("Exit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(Left)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(up)
                            .addGap(159, 159, 159))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Down)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exit)
                            .addGap(33, 33, 33)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(value, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Right)
                        .addGap(76, 76, 76))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(up)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Left)
                            .addComponent(value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Right))
                        .addGap(18, 18, 18)
                        .addComponent(Down)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(exit)
                        .addGap(25, 25, 25))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valueActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Down;
    private javax.swing.JButton Left;
    private javax.swing.JButton Right;
    private javax.swing.JButton exit;
    private javax.swing.JButton up;
    private javax.swing.JTextField value;
    // End of variables declaration//GEN-END:variables
}
