
package graphicseditor;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.RenderedImage;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;


public class Save extends javax.swing.JFrame {

    PaintSurface paint_surface;
    /**
     * Creates new form Save
     */
    public Save(PaintSurface ps) {
        paint_surface = ps;
        initComponents();

        done.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Thread t = new Thread(new Runnable(){
                    public void run(){
                        String file = filename.getText();
                        try {
                            ObjectOutputStream os = new ObjectOutputStream(new FileOutputStream(file+"Rect.ser"));
                            os.writeObject(paint_surface.getRect_array());
                            os.close();
                            os = new ObjectOutputStream(new FileOutputStream(file + "Ellipse.ser"));
                            os.writeObject(paint_surface.getEllipse_array());
                            os.close();
                            os = new ObjectOutputStream(new FileOutputStream(file + "Line.ser"));
                            os.writeObject(paint_surface.getLine_array());
                            os.close();
                            os = new ObjectOutputStream(new FileOutputStream(file + "group.ser"));
                            os.writeObject(paint_surface.getGroup_array());
                            os.close();
                            os = new ObjectOutputStream(new FileOutputStream(file + "Images.ser"));
                            for (Image i : paint_surface.getImages()){
                                ImageIO.write((RenderedImage) i, "png", os);
                            }
                            os.close();
                            os = new ObjectOutputStream(new FileOutputStream(file+"Img_Rect.ser"));
                            os.writeObject(paint_surface.getImg_rect());
                            os.close();
                            dispose();
                        } catch (FileNotFoundException ex) {
                            Logger.getLogger(Save.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Save.class.getName()).log(Level.SEVERE, null, ex);
                        }


                    }

                });
                t.start();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filename = new javax.swing.JTextField();
        done = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        filename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filenameActionPerformed(evt);
            }
        });

        done.setText("Ok");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(filename, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(done)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(filename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(done)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filenameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton done;
    private javax.swing.JTextField filename;
    // End of variables declaration//GEN-END:variables
}
